G6capstone-AI_Education: app.ImagePreprocessing.ImagePreprocessing Class Reference
app.ImagePreprocessing.ImagePreprocessing Class Reference
Public Member Functions
def getAdvancedFeatures (imageIn)
def avgGray (image)
def avgRed (image)
def avgGreen (image)
def avgBlue (image)
def numBrownRed (image)
def numBrownGreen (image)
def numBrownBlue (image)
def FdHuMoments (image)
def FdHaralick (image)
def FdHistogram (image, mask=None, bins=8)
def ImageProcessing (folder_name)
Static Public Attributes
feature_vector
tuple columnLabels
blighted_features = allFilesInDir('images/blighted', 'B')
healthy_features = allFilesInDir('images/healthy', 'H')
csvfile = open('csvOut.csv','w', newline = '')
obj = csv.writer(csvfile)
string folder_name = 'images/'
Detailed Description
@package ImagePreprocessing
This class extracts a number of features from the images and saves them in a CSV
to be used by the machine learning class.
Member Function Documentation
avgBlue()
def app.ImagePreprocessing.ImagePreprocessing.avgBlue (image)
Referenced by app.ImagePreprocessing.ImagePreprocessing.ImageProcessing().
avgGray()
def app.ImagePreprocessing.ImagePreprocessing.avgGray (image)
Referenced by app.ImagePreprocessing.ImagePreprocessing.ImageProcessing().
avgGreen()
def app.ImagePreprocessing.ImagePreprocessing.avgGreen (image)
Referenced by app.ImagePreprocessing.ImagePreprocessing.ImageProcessing().
avgRed()
def app.ImagePreprocessing.ImagePreprocessing.avgRed (image)
Referenced by app.ImagePreprocessing.ImagePreprocessing.ImageProcessing().
FdHaralick()
def app.ImagePreprocessing.ImagePreprocessing.FdHaralick (image)
Referenced by app.ImagePreprocessing.ImagePreprocessing.ImageProcessing().
FdHistogram()
def app.ImagePreprocessing.ImagePreprocessing.FdHistogram (image, mask = None, bins = 8)
Extracts color histogram feature from an image
Parameters
----------
image : imread
    The image used for feature extraction
Returns
-------
Feature : Float Array
    The color histogram in the image.
Reference
---------
https://gogul.dev/software/image-classification-python
FdHuMoments()
def app.ImagePreprocessing.ImagePreprocessing.FdHuMoments (image)
Extracts Hu moments feature from an image
Parameters
----------
image : imread
    The image used for feature extraction
Returns
-------
Feature : Float Array
    The Hu moments in the image.
Reference
---------
https://gogul.dev/software/image-classification-python
Referenced by app.ImagePreprocessing.ImagePreprocessing.ImageProcessing().
getAdvancedFeatures()
def app.ImagePreprocessing.ImagePreprocessing.getAdvancedFeatures (imageIn)
Returns a tuple of advanced features.
Parameters
----------
imageIn : Image
    The image to process.
Returns
-------
returnValues : tuple
    numbers.
Referenced by app.ImagePreprocessing.ImagePreprocessing.ImageProcessing().
ImageProcessing()
def app.ImagePreprocessing.ImagePreprocessing.ImageProcessing (folder_name)
References app.ImagePreprocessing.ImagePreprocessing.avgBlue(), app.ImagePreprocessing.ImagePreprocessing.avgGray(), app.ImagePreprocessing.ImagePreprocessing.avgGreen(), app.ImagePreprocessing.ImagePreprocessing.avgRed(), app.ImagePreprocessing.ImagePreprocessing.FdHaralick(), app.ImagePreprocessing.ImagePreprocessing.FdHuMoments(), app.ImagePreprocessing.ImagePreprocessing.getAdvancedFeatures(), app.ImagePreprocessing.ImagePreprocessing.numBrownBlue(), app.ImagePreprocessing.ImagePreprocessing.numBrownGreen(), and app.ImagePreprocessing.ImagePreprocessing.numBrownRed().
numBrownBlue()
def app.ImagePreprocessing.ImagePreprocessing.numBrownBlue (image)
Referenced by app.ImagePreprocessing.ImagePreprocessing.ImageProcessing().
numBrownGreen()
def app.ImagePreprocessing.ImagePreprocessing.numBrownGreen (image)
Referenced by app.ImagePreprocessing.ImagePreprocessing.ImageProcessing().
numBrownRed()
def app.ImagePreprocessing.ImagePreprocessing.numBrownRed (image)
Referenced by app.ImagePreprocessing.ImagePreprocessing.ImageProcessing().
Member Data Documentation
blighted_features
app.ImagePreprocessing.ImagePreprocessing.blighted_features = allFilesInDir('images/blighted', 'B') static
columnLabels
tuple app.ImagePreprocessing.ImagePreprocessing.columnLabels static
Initial value:
=  ('fileName','fvhu','fvhu2','fvhu3','fvhu4','fvhu5','fvhu6','fvhu7',
                        'fvha1','fvha2','fvha3','fvha4','fvha5','fvha6','fvha7','fvha7',
                        'fvha8','fvha9','fvha10','fvha11','fvha12',
                        'gray_mean', 'red_mean', 'green_mean', 'blue_mean', 'num_brown_red', 'num_brown_green',
                        'num_brown_blue', 'numForegroundPxls', 'blightedHSV_pxls', 'blightedHSV_ratio',
                        'numRGB_blightedPxls', 'blightedRGBRatio', 'RGB_and_HSV_blighted', 'RGB_and_HSV_both_ratio', 'label')
csvfile
app.ImagePreprocessing.ImagePreprocessing.csvfile = open('csvOut.csv','w', newline = '') static
feature_vector
app.ImagePreprocessing.ImagePreprocessing.feature_vector static
Initial value:
=  np.hstack([file, fv_hu_moments, fv_haralick, gray_mean, red_mean, green_mean, blue_mean,
                                                num_brown_red, num_brown_green, num_brown_blue, advanced_features[0],
                                                advanced_features[1],  advanced_features[2],  advanced_features[3],
                                                 advanced_features[4],  advanced_features[5],  advanced_features[6], label])
folder_name
string app.ImagePreprocessing.ImagePreprocessing.folder_name = 'images/' static
healthy_features
app.ImagePreprocessing.ImagePreprocessing.healthy_features = allFilesInDir('images/healthy', 'H') static
obj
app.ImagePreprocessing.ImagePreprocessing.obj = csv.writer(csvfile) static
The documentation for this class was generated from the following file:
G6capstone-AI_Education/app/ImagePreprocessing.py