G6capstone-AI_Education: app.web Namespace Reference
app.web Namespace Reference
Functions
def getData ()
def createMLModel (data)
def renderLabel (form)
def initializeAL (form, confidence_break=.7)
def getNextSetOfImages (form, sampling_method)
def prepairResults (form)
def findCorrect (max_num_images)
def pullUserData ()
def home ()
def leaderboards ()
def label ()
def login ()
def logout ()
def register ()
def profile ()
def previousSelections ()
def clearData ()
def intermediate ()
def final ()
def feedback (h_list, u_list, h_conf_list, u_conf_list)
def gamemode ()
Variables
bootstrap = Bootstrap(app)
Function Documentation
clearData()
def app.web.clearData ()
Operates the clear database button in the profile page.
createMLModel()
def app.web.createMLModel (data)
Prepares the training set and creates a machine learning model using the training set.
Parameters
----------
data : Pandas DataFrame
    The data that contains the features for each image
Returns
-------
ml_model : ML_Model class object
    ml_model created from the training set.
train_img_names : String
    The names of the images.
Referenced by app.web.getNextSetOfImages(), and app.web.prepairResults().
feedback()
def app.web.feedback (h_list, u_list, h_conf_list, u_conf_list)
Operates the feedback(feedback.html) web page.
final()
def app.web.final ()
Operates the final(final.html) web page.
findCorrect()
def app.web.findCorrect (max_num_images)
Finds the images the user labeled correctly and incorrectly
Parameters
----------
max_num_images integar for use in stoping the function early in case of finding previous accuracy rates
Returns
-------
Lists accuracy, correct, incorrect, cor_label, inc_label
    and number of images
These will hold image names that are correct and incorrect
References app.web.pullUserData().
Referenced by app.web.gamemode(), app.web.previousSelections(), and app.web.profile().
gamemode()
def app.web.gamemode ()
Operates the gamemode(gamemode.html) web page.
find relavant information
References app.web.findCorrect().
getData()
def app.web.getData ()
Gets and returns the csvOut.csv as a DataFrame.
Returns
-------
data : Pandas DataFrame
    The data that contains the features for each image.
Referenced by app.web.getNextSetOfImages(), app.web.initializeAL(), and app.web.prepairResults().
getNextSetOfImages()
def app.web.getNextSetOfImages (form, sampling_method)
Uses a sampling method to get the next set of images needed to be labeled.
Parameters
----------
form : LabelForm class object
    form to be used when displaying label.html
sampling_method : SamplingMethods Function
    function that returns the queue and the new test set that does not contain the queue.
Returns
-------
render_template : flask function
    renders the label.html webpage.
References app.web.createMLModel(), app.web.getData(), and app.web.renderLabel().
Referenced by app.web.label().
home()
def app.web.home ()
Operates the root (/) and index(index.html) web pages.
initializeAL()
def app.web.initializeAL (form, confidence_break = .7)
Initializes the active learning model and sets up the webpage with everything needed to run the application.
Parameters
----------
form : LabelForm class object
    form to be used when displaying label.html
confidence_break : number
    How confident the model is.
Returns
-------
render_template : flask function
    renders the label.html webpage.
References app.web.getData(), app.web.prepairResults(), and app.web.renderLabel().
Referenced by app.web.label().
intermediate()
def app.web.intermediate ()
Operates the intermediate(intermediate.html) web page.
label()
def app.web.label ()
Operates the label(label.html) web page.
References app.web.getNextSetOfImages(), app.web.initializeAL(), app.web.prepairResults(), and app.web.renderLabel().
leaderboards()
def app.web.leaderboards ()
Operates the leaderboards(leaderboards.html) web page.
login()
def app.web.login ()
Operates the login(login.html) web page.
logout()
def app.web.logout ()
Operates the logout button.
prepairResults()
def app.web.prepairResults (form)
Creates the new machine learning model and gets the confidence of the machine learning model.
Parameters
----------
form : LabelForm class object
    form to be used when displaying label.html
Returns
-------
render_template : flask function
    renders the appropriate webpage based on new confidence score.
Here if use is logged in and has a database entry then we need to append those to the session labels else append from latest form choice
References app.web.createMLModel(), and app.web.getData().
Referenced by app.web.initializeAL(), and app.web.label().
previousSelections()
def app.web.previousSelections ()
Operates the previousSelections(previous.html) web page.
References app.web.findCorrect().
profile()
def app.web.profile ()
Operates the profile(profile.html) web page.
References app.web.findCorrect().
pullUserData()
def app.web.pullUserData ()
Returns the current user and their confidence data if applicable
Parameters
----------
None
Returns
-------
SQLAlchemy datatypes for user and confidence tabels
This function will be used to replace all the if/else statements throughout the code to clean it up a bit
Referenced by app.web.findCorrect().
register()
def app.web.register ()
Operates the register(register.html) web page.
renderLabel()
def app.web.renderLabel (form)
prepairs a render_template to show the label.html web page.
Parameters
----------
form : LabelForm class object
    form to be used when displaying label.html
Returns
-------
render_template : flask function
    renders the label.html webpage.
Referenced by app.web.getNextSetOfImages(), app.web.initializeAL(), and app.web.label().
Variable Documentation
bootstrap
app.web.bootstrap = Bootstrap(app)